---
- name: Stop the role if ludus_elastic_enrollment_token is not set
  ansible.builtin.debug:
    msg: "ludus_elastic_enrollment_token is not set. Attempting to get one automatically."
  when: ludus_elastic_enrollment_token == ""

- name: Get an enrollment token automatically
  ansible.builtin.include_role:
    file: get_token.yml
  when: ludus_elastic_enrollment_token == ""

- name: Setup Elastic agent on a Windows machine
  ansible.builtin.include_role:
    file: windows.yml
  when: ansible_os_family == "Windows"

- name: Setup Elastic agent on a Debian based machine
  ansible.builtin.include_role:
    file: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Tell the user to check the Kibana Dashboard
  ansible.builtin.debug:
    msg: "Check the Kibana Dashboard for the status of the Elastic agent!"
