- name: Check if Elastic agent bin exists on Ludus for Windows targets
  ansible.builtin.stat:
    path: "/opt/ludus/resources/windows/elastic-agent-{{ ludus_elastic_agent_version }}-windows-x86_64.zip"
  register: windows_agent_exists
  delegate_to: localhost

- name: Download the Windows Elastic agent if it doesn't exist
  ansible.builtin.get_url:
    url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ ludus_elastic_agent_version }}-windows-x86_64.zip"
    dest: "/opt/ludus/resources/windows/elastic-agent-{{ ludus_elastic_agent_version }}-windows-x86_64.zip"
    mode: "0644"
  delegate_to: localhost
  when: not windows_agent_exists.stat.exists

- name: Create Ludus directory on Windows target if it doesn't exist
  ansible.windows.win_file:
    path: C:\ludus
    state: directory

- name: Copy Elastic agent to Windows target
  ansible.windows.win_copy:
    src: "/opt/ludus/resources/elastic/elastic-agent-{{ ludus_elastic_agent_version }}-windows-x86_64.zip"
    dest: "C:\\ludus"

- name: Uninstall Elastic agent if installed on Windows
  ansible.windows.win_shell: "& 'C:\\Program Files\\Elastic\\Agent\\elastic-agent.exe' uninstall -f"
  ignore_errors: true

- name: Unzip Elastic agent on Windows target
  ansible.windows.win_shell: "Expand-Archive -Path 'C:\\ludus\\elastic-agent-{{ ludus_elastic_agent_version }}-windows-x86_64.zip' -force -DestinationPath 'C:\\ludus'"

- name: Install Elastic agent on Windows target
  ansible.windows.win_shell: "C:\\ludus\\elastic-agent-{{ ludus_elastic_agent_version }}-windows-x86_64\\elastic-agent.exe install --url={{ ludus_elastic_fleet_server }} --enrollment-token={{ ludus_elastic_enrollment_token }} --force --insecure"
